package com.and.domain.model.type

enum class InterestCategory(val value: String) {
    INTEREST_ECONOMY_AFFAIRS("경제·시사"),
    INTEREST_BUSINESS("비즈니스"),
    INTEREST_SCIENCE_TECH("과학·기술"),
    INTEREST_TREND("트렌드"),
    INTEREST_FINANCE("재테크"),
    INTEREST_CONTENTS("콘텐츠"),
    INTEREST_LIFESTYLE("라이프스타일"),
    INTEREST_HOBBY("취미·자기계발"),
    INTEREST_HEALTH("건강·의학"),
    INTEREST_MENTAL_CARE("멘탈케어"),
    INTEREST_FOOD_DRINK("푸드·드링크"),
    INTEREST_NATURE_ENVIRONMENT("자연·환경"),
    INTEREST_LIVING_INTERIOR("리빙·인테리어"),
    INTEREST_ART_DESIGN("미술·디자인"),
    INTEREST_MUSIC("음악"),
    INTEREST_GAME("게임·스포츠"),
    INTEREST_CONCERT_PERFORMANCE("콘서트·공연"),
    INTEREST_CULTURE("문화"),
    INTEREST_LITERATURE_BOOK("문학·도서"),
    INTEREST_LANGUAGE("언어"),
    INTEREST_MOVIE("영화"),
    INTEREST_TRAVEL("지역·여행"),
    INTEREST_FAMILY("가족"),
    INTEREST_SHOPPING("쇼핑"),
    INTEREST_PET("반려동물"),
    INTEREST_SOCIAL_CONTRIBUTION("사회공헌");
}